version: "3"

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: gunicorn --bind :8000 config.wsgi:application
    volumes:
      - ./backend:/backend:cached
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    depends_on:
      - mysql
    networks:
      - frontend
      - backend

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    command: sh -c "npm -g config set registry http://registry.npmjs.org/ &&
             cd /app && npm start"
    volumes:
      - ./frontend/app:/app:cached
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    networks:
      - frontend

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/app/build:/var/www/http
    depends_on:
      - backend
      - frontend
    networks:
      - frontend

  mysql:
    container_name: mysql
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql/db_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge